name: Elevator
version: 1.0.0
main: de.mcbesser.elevator.ElevatorPlugin
api-version: '26.1.1'
author: McB_sser
description: Ein Minecraft Elevator Plugin mit vertikalen Druckplatten-Fahrst\u00fchlen.
